# Generated by Django 4.2.5 on 2023-11-15 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_message_time_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='User_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpt_model', models.TextField(default='gpt-3.5-turbo-1106')),
                ('messages_till_profile_update', models.PositiveSmallIntegerField(default=5)),
                ('messages_for_profile_update', models.PositiveSmallIntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
