# Generated by Django 4.2.5 on 2023-11-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_is_bot_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_settings',
            name='messages_for_input_extraction',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='content',
            field=models.TextField(max_length=4000),
        ),
    ]
