# Generated by Django 4.2.5 on 2023-12-04 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_user_settings_messages_for_input_extraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_settings',
            name='messages_till_journal_update',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='gpt_model',
            field=models.TextField(default='gpt-3.5-turbo'),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='messages_for_input_extraction',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='User_emotional_journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.TextField(max_length=3000)),
                ('updates_count', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
