# Generated by Django 4.2.5 on 2023-12-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_gpt_model_user_settings_journal_gpt_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_settings',
            name='responder_personality',
            field=models.TextField(default=2, max_length=2500),
            preserve_default=False,
        ),
    ]
