# Generated by Django 4.2.5 on 2023-12-29 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_settings_responder_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_emotional_journal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='responder_personality',
            field=models.TextField(default='Caring and helpful assistant.', max_length=2500),
        ),
    ]
