# Generated by Django 4.2.5 on 2023-12-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_emotional_journal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_settings',
            name='messages_for_journal_update',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
