# Generated by Django 4.2.5 on 2023-12-31 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_user_settings_messages_for_journal_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balance_transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_balance')),
            ],
        ),
    ]
