# Generated by Django 4.2.5 on 2024-01-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_balance_balance_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balance_transactions',
            new_name='Balance_transaction',
        ),
        migrations.AlterField(
            model_name='user_emotional_journal',
            name='journal',
            field=models.TextField(default='{}', max_length=3000),
        ),
    ]
